project:
  type: website
  output-dir: docs  # GitHub Pages will use this as the deployment folder

website:
  title: "DSAN 5900 HW1 Website"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: notebooks/
        text: Notebooks
      - href: code/
        text: Code
      - href: data/
        text: Data
